dist: bionic
language: php

php:
  - 7.3

before_install:
  - travis_retry composer self-update
  - composer config discard-changes true

before_script:
  - composer install --prefer-dist --no-interaction

script:
  - vendor/bin/phpunit -c phpunit.xml --testdox --verbose

matrix:
  fast_finish: true
